### ISSUE TITLE
BridgeSupport problem?

### ISSUE THREAD

**Issue by jviney** [mattgreen/motion-sqlite3#4]
Hi,

I've just started with RubyMotion and your sqlite3 driver was working great. But after upgrading RubyMotion to 2.22 (from 2.18), 

```
     Build ./build/iPhoneSimulator-7.0-Development
   Compile /Users/jviney/Work/rm/nzf-1/vendor/bundle/ruby/2.0.0/gems/motion-sqlite3-0.5.0/lib/motion-sqlite3/version.rb
   Compile /Users/jviney/Work/rm/nzf-1/vendor/bundle/ruby/2.0.0/gems/motion-sqlite3-0.5.0/lib/motion-sqlite3/result_set.rb
   Compile /Users/jviney/Work/rm/nzf-1/vendor/bundle/ruby/2.0.0/gems/motion-sqlite3-0.5.0/lib/motion-sqlite3/error.rb
   Compile /Users/jviney/Work/rm/nzf-1/vendor/bundle/ruby/2.0.0/gems/motion-sqlite3-0.5.0/lib/motion-sqlite3/statement.rb
2014-02-06 18:46:15.936 ruby[43808:d0f] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x62c1af0 {NSLocalizedDescription=zero length data}
2014-02-06 18:46:15.941 ruby[43807:d0f] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x5d0aed0 {NSLocalizedDescription=zero length data}
r
```

The bizarre thing is that if I create a new RubyMotion project and copy the application code in, it works fine.

Any idea what's causing this error?

P.S. Thanks for writing this library!

**Comment by wallclimber21** [comment]
I think I'm running into the same problem. I simply cloned the repo, ran 'bundle', then 'rake'.
I get the following:
```
     Build ./build/iPhoneSimulator-8.2-Development
   Compile /Users/tom/projects/motion-sqlite3/lib/motion-sqlite3/result_set.rb
   Compile /Users/tom/projects/motion-sqlite3/lib/motion-sqlite3/version.rb
   Compile /Users/tom/projects/motion-sqlite3/lib/motion-sqlite3/database.rb
   Compile /Users/tom/projects/motion-sqlite3/lib/motion-sqlite3/error.rb
   Compile /Users/tom/projects/motion-sqlite3/lib/motion-sqlite3/statement.rb
   Compile ./app/app_delegate.rb
2015-03-30 22:27:43.332 ruby[72811:1941863] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x7e5c5500 {NSLocalizedDescription=zero length data}
2015-03-30 22:27:43.360 ruby[72804:1941856] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x7e321310 {NSLocalizedDescription=zero length data}
2015-03-30 22:27:43.370 ruby[72810:1941862] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x7ec84230 {NSLocalizedDescription=zero length data}
2015-03-30 22:27:43.371 ruby[72808:1941860] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x803a3a90 {NSLocalizedDescription=zero length data}
2015-03-30 22:27:43.372 ruby[72809:1941861] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x80ebc910 {NSLocalizedDescription=zero length data}
2015-03-30 22:27:43.378 ruby[72806:1941858] can't open BridgeSupport full file at path `build/sqlite3.bridgesupport': Error Domain=NSXMLParserErrorDomain Code=4 "zero length data" UserInfo=0x7fe0bea0 {NSLocalizedDescription=zero length data}
rake aborted!
Command failed with status (1): [/usr/bin/env VM_PLATFORM="iPhoneSimulator"...]
/Library/RubyMotion/lib/motion/project/builder.rb:144:in `block (2 levels) in build'
/Library/RubyMotion/lib/motion/project/builder.rb:130:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:130:in `block in build'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `call'
/Library/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `block (2 levels) in initialize'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
```
I'm using rvm with ruby 2.2.0, and rubymotion version 3.8.

**Comment by mattgreen** [comment]
I've seen people having success recently, but only with the master branch of `motion.h`. Give that a try.

**Comment by ben5516** [comment]
I'm having this problem on High Sierra with motion 5.3 . Has anyone found a solution for this? I've tried the above fixes to no avail.
